---
abstract: 'Loads all features of the current used version of Perl.'
author:
  - 'Juergen von Brietzke <juergen.von.brietzke@t-online.de>'
build_requires:
  Test::More: '0'
  Test::Pod: '1.14'
  Test::Pod::Coverage: '1.04'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4214, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-Modern-Perl
provides:
  Perl::Modern::Perl:
    file: lib/Perl/Modern/Perl.pm
    version: '1.010'
requires:
  Carp: '0'
  English: '0'
  Exporter: '0'
  IO::File: '0'
  IO::Handle: '0'
  Perl::Version: '0'
  feature: '0'
  mro: '0'
  perl: '5.012'
  strict: '0'
  version: '0'
  warnings: '0'
version: '1.010'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
